version: 2
updates:
- package-ecosystem: composer
  directory: "/api"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: illuminate/support
    versions:
    - 8.32.1
  - dependency-name: illuminate/config
    versions:
    - 8.31.0
    - 8.38.0
  - dependency-name: illuminate/log
    versions:
    - 8.28.1
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: riot
    versions:
    - "> 3.13.2"
  - dependency-name: copy-webpack-plugin
    versions:
    - 8.1.0
  - dependency-name: webpack
    versions:
    - 5.23.0
- package-ecosystem: docker
  directory: "/api"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: php
    versions:
    - 8.0.3.pre.fpm.pre.alpine
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
