---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
ratings:
  paths:
  - "**.js"
  - "**.tag"
  - "**.php"
exclude_paths:
- "app/tests/"
