language: php

php:
  - 7.1

services:
  - docker

env:
  global:
    secure: Kb4xo7pjWMuhemVHJWreBwtoq3Lqob6TvzOKht6eXD6jhA1UE+Yxy5yQnozJ2pnQkUgW37avwOtm5D6Znw7byXU94wBAUwyIcymiihZulMZu27WrQUkWp1Zajq4xdz6xa7gVPVRjjW9CTQM+2rxU/4yznETrgUF7XjKbXBiD2qSQW/3wXw3lzz96WAUwpVUEcsAEJSzuYTb2IVcTC/cF/YIQD9Z6NJJenCgtK6Ix4KVk/Bq5F29BRpT5qiHSSoWoAeg5kOdb/Sz7+M2tukcD8wK13jLZ5YJ5NH/9A0E3BZvy4gug1IPv4Gd3DXTlyPhsQGANnanSPAc8xAQRSYJ7ax6FTFYq9cxsi1oFL/lqFJ6SWlk582Q1sXbekbiY0iZPoivcVKTdn2OU3JR5Jpuh4HR8YSycT0fJYqQRZeNePByw7MuyCEXQvTYP+9nYt/hWzvp9SefoN+qlGhoOE3VQARu38s4otYlkAj0K4bqAo465GGH72Uv7+UhlBpOGBHEHW+b0qKgRKqdIuNXm7//cG+FCVYggj0zuQJIZPRT+iD/FQK+J0lbrhO89oU5Za9FmwyIDj9bgT/uD7TdJk7Bkk0zRsusOCn4O5IOVC8A8wPce7dnYijr3wgadYYSrgV4fW8rHgitnHxnhZQoZQeH0PLHCxY13FXZTZQ3ey15FMqA=

before_script:
  - bin/.travis/before_script

script:
  - bin/init
  - bin/test

after_success:
  - bin/.travis/after_success
