language: php

php:
  - 7.1

services:
  - docker

env:
  global:
    secure: Ncm8rpQ4RNDYblbnHawymg+HPYxWuQte6FZbf2dVmtqmJir3FNNta5ScBlNlfRS10N3+TkTK7UVr7nR/Xb750V4E+NOwt+kj7xe2uUK+gMEltK7cTFF2sV/vo45im6LxO9wFJfA4Xnb4kqW+F4tpIM4t1L2YmPosKZCkhADJEZ+VrDZ7NkMaZGXISy/Yy1ftv7pJtp4Sk/DQV8GTv/XIqRi6D8K+pdPmYOoSeKVPcFb1dDwG97miHQP0BVGrTk3DcNfftnWcYqsDIybRTRt2J0z6hL5B6rhTyCkuYYGs+t+O3TXhjd2c8In6w9i/8JqxHlxm3gTTjjL1mK3dVdGHJ4AcpF9gngoeGMx2qB+LpIAfTObfqEe01TqhcLGDakarJOhdQ2NE3QRbIGYqsotRYEmcogJiOHTcGkrSoma4mGeUdEk6BpLwDyOweW/99/XOHqRDYEG/xAjhBUMv38tuF7qKTNjq8FgADPHf+QX+zfQ3rqRPx1UZxrzfhgHeAVz6scLLsN5TWtQIZBo1r6ir1dUXozKJPHsyUBO5Zx1H6+K21mmt3r+LH0/MPwQ+VmiWvS3IFeuTz91P1+NsFCR22ey5iNWkV9unwB5j/9oO3sz2u16tPgCFRbNsDVdnEMUTtzJM29FTWvgpCFQbHaDCN0TMbihuIJ8MVz7DElhNDsI=

before_script:
  - bin/.travis/before_script

script:
  - bin/init
  - bin/test

after_success:
  - bin/.travis/after_success
