language: node_js
node_js: '7'

cache:
  directories:
  - node_modules

env:
  global:
    secure: sWDdir8/dR1W7v/7uxRLElSGZKaBVewpg6H0po/WL5RIWqxxsy954QOkzMPYarI40HkG0sKL86Bb+Ug2T5DncthDmYT//6LFX7cMBpnK9uOwIq9jajT7YZnNxEZM09CO0/gj5F672xQMc74I8CsZkvxAEl/ZwRLiga/vzOS5L4gfczxt8drW19qvfs9eE4OzjnOw9FzSgRWrrtxcqEQEcS+oTgeXrq0HpH0ebHBu+ItpR2MgiDyffcAdx3UFu7GISSemMhRC8Ww0HkaiR8lj+RgHh75AscwzdZuhuU7EuUvOX41HpMMb1Rhbh9a4HMHz2q17rTkwlmqe8qQzMmPJnBotcs8+snbnRSBiaJjqekm6oaZ/ieG+J8Z3EYRHnhezEzPZirPbB5QRqpwe+UlLx4LfoFralTiYcuhT9Cu/6drTOB985ejJjN75Phb0NxN6ynvADoXbb+IO7b+jw1IwBGUaH42FXqdsH/uDO4H4Fqc0NfN75/dfxgYO1uCF3XONFuxlEs5dk1ALxsBREKuK9jbRloYakFhmN8Fkuh+8HotQEtY1U7VMBA3b2mY0k1B3T/zRzCzF9kcZmwfX7PJ4Ild/YeBnY2LS0KH6/TOwF8DVmITSVPwsZZC/JP7vCpxHnoGj4OJT9dnG3CkLdb6V698w46ld1ayHB0K/7Bfqoeo=

before_install:
- if [ "$TRAVIS_BRANCH" != "master" ] || [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    return 0;
  fi
- openssl aes-256-cbc -K $encrypted_32aa7ee0d8d8_key -iv $encrypted_32aa7ee0d8d8_iv
  -in ssh.tar.enc -out ssh.tar -d
- tar xvf ssh.tar
- mv id_rsa config ~/.ssh
- chmod 600 ~/.ssh/id_rsa

install:
- npm install

before_script:
- git remote add homo $TARGET

script:
- npm start

after_success:
- if [ "$TRAVIS_BRANCH" != "master" ] || [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    exit 0;
  fi
- git push homo master
