version: "2.1"

services:
  api:
    build:
      context: ./api
      target: runtime
    working_dir: /var/www/html/api
    command: composer test
    volumes:
      - type: bind
        source: .
        target: /var/www/html

  build:
    build:
      context: .
      target: build
    working_dir: /usr/src/app/client
    command: npm run build
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
