version: "2.1"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    working_dir: /var/www/html/api
    environment:
      HOMOCHECKER_DB_HOST: database
      HOMOCHECKER_DB_USERNAME: homo
      HOMOCHECKER_DB_PASSWORD: homo
      HOMOCHECKER_REDIS_HOST: redis
      HOMOCHECKER_TWITTER_CONSUMER_KEY:
      HOMOCHECKER_TWITTER_CONSUMER_SECRET:
      HOMOCHECKER_TWITTER_TOKEN:
      HOMOCHECKER_TWITTER_TOKEN_SECRET:
    volumes:
      - .:/var/www/html
    networks:
      - default
      - ipv6

  build:
    image: node:14.9
    working_dir: /usr/src/app/client
    command: npm run watch
    environment:
      HOMOCHECKER_ENV: "${HOMOCHECKER_ENV-development}"
    volumes:
      - .:/usr/src/app

  client:
    image: nginx:1.19
    ports:
      - "${HOMOCHECKER_PORT-4545}:80"
    volumes:
      - ./client/dist:/var/www/html
      - ./client/conf:/etc/nginx/conf.d
    networks:
      - default

  database:
    image: mysql:8.0
    command: [--character-set-server=utf8, --default-authentication-plugin=mysql_native_password]
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homo
      MYSQL_USER: homo
      MYSQL_PASSWORD: homo
      MYSQL_ROOT_PASSWORD: homo
    networks:
      - default

  redis:
    image: redis:6.0
    networks:
      - default

volumes:
  database:
    driver: local

networks:
  ipv6:
