version: "2.1"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    working_dir: /var/www/html/api
    command: composer test
    volumes:
      - .:/var/www/html
    environment:
      - TRAVIS
      - TRAVIS_JOB_ID

  build:
    image: node:13.3
    working_dir: /usr/src/app
    command: npm run build
    volumes:
      - ./client:/usr/src/app
