version: "2.1"

services:
  api:
    build:
      context: ./api
      target: runtime
    working_dir: /var/www/html/api
    environment:
      HOMOCHECKER_DB_HOST: database
      HOMOCHECKER_DB_USERNAME: homo
      HOMOCHECKER_DB_PASSWORD: homo
      HOMOCHECKER_REDIS_HOST: redis
      HOMOCHECKER_TWITTER_CONSUMER_KEY:
      HOMOCHECKER_TWITTER_CONSUMER_SECRET:
      HOMOCHECKER_TWITTER_TOKEN:
      HOMOCHECKER_TWITTER_TOKEN_SECRET:
    volumes:
      - type: bind
        source: .
        target: /var/www/html
    networks:
      - default
      - ipv6

  build:
    build:
      context: .
      target: build
    working_dir: /usr/src/app/client
    command: npm run watch
    environment:
      HOMOCHECKER_ENV: "${HOMOCHECKER_ENV-development}"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app

  client:
    image: nginx:1.19-alpine
    ports:
      - "${HOMOCHECKER_PORT-4545}:80"
    volumes:
      - type: bind
        source: ./client/dist
        target: /var/www/html
      - type: bind
        source: ./client/conf
        target: /etc/nginx/conf.d
    networks:
      - default

  database:
    image: postgres:13.2
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - database:/var/lib/postgres/data
    environment:
      POSTGRES_DB: homo
      POSTGRES_USER: homo
      POSTGRES_PASSWORD: homo
    networks:
      - default

  redis:
    image: redis:6.2
    networks:
      - default

volumes:
  database:
    driver: local

networks:
  ipv6:
