version: "2.1"

services:
  api:
    build: ./api
    links:
      - database
    working_dir: /var/www/html/api
    command: composer test
    volumes:
      - .:/var/www/html
    environment:
      - TRAVIS
      - TRAVIS_JOB_ID

  build:
    image: node:8.4
    working_dir: /usr/src/app
    command: npm run build
    volumes:
      - ./client:/usr/src/app

  database:
    image: mysql:5.7
    command: [--character-set-server=utf8]
    environment:
      MYSQL_DATABASE: homo
      MYSQL_USER: homo
      MYSQL_PASSWORD: homo
      MYSQL_ROOT_PASSWORD: homo
