version: "3.9"

services:
  api:
    build:
      context: ./api
      target: dev
    working_dir: /var/www/html/api
    command: composer test
    volumes:
      - type: bind
        source: ./api
        target: /var/www/html/api

  build:
    build:
      context: .
      target: dev
    working_dir: /usr/src/app/client
    command: npm run --no-update-notifier build
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
