version: "2.1"

services:
  api:
    build: ./api
    links:
      - database
      - redis
    working_dir: /var/www/html/api
    volumes:
      - ./api:/var/www/html/api
    networks:
      - default

  build:
    image: node:11.6
    working_dir: /usr/src/app
    command: npm run watch
    environment:
      HOMOCHECKER_ENV: "${HOMOCHECKER_ENV-production}"
    volumes:
      - ./client:/usr/src/app

  client:
    image: nginx:1.15
    links:
      - api
    ports:
      - "${HOMOCHECKER_PORT-4545}:80"
    volumes:
      - ./client/dist:/var/www/html
      - ./client/conf:/etc/nginx/conf.d
    networks:
      - default

  database:
    image: mysql:5.7
    command: [--character-set-server=utf8]
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homo
      MYSQL_USER: homo
      MYSQL_PASSWORD: homo
      MYSQL_ROOT_PASSWORD: homo
    networks:
      - default

  redis:
    image: redis:5.0
    networks:
      - default

volumes:
  database:
    driver: local

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "${HOMOCHECKER_SUBNET6-fd00:4545::/48}"
          gateway: "${HOMOCHECKER_GATEWAY6-fd00:4545::1}"
        - subnet: "${HOMOCHECKER_SUBNET4-10.45.45.0/24}"
          gateway: "${HOMOCHECKER_GATEWAY4-10.45.45.1}"
