version: "2.1"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    working_dir: /var/www/html/api
    command: composer test
    volumes:
      - .:/var/www/html

  build:
    image: node:14.0
    working_dir: /usr/src/app/client
    command: npm run build
    volumes:
      - .:/usr/src/app
