version: "2.1"

services:
  api:
    build: ./api
    working_dir: /var/www/html/api
    command: composer test
    volumes:
      - .:/var/www/html
    environment:
      - TRAVIS
      - TRAVIS_JOB_ID

  build:
    image: node:12.6
    working_dir: /usr/src/app
    command: npm run build
    volumes:
      - ./client:/usr/src/app

  database:
    image: mysql:8.0
    command: [--character-set-server=utf8, --default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_DATABASE: homo
      MYSQL_USER: homo
      MYSQL_PASSWORD: homo
      MYSQL_ROOT_PASSWORD: homo
