FROM php:7.4.7-fpm-alpine

RUN apt-get -y update && \
    apt-get -y install git unzip

RUN curl -sSfL 'https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer' | php -- --quiet && \
    mv composer.phar /usr/bin/composer && \
    pecl install redis && \
    docker-php-ext-enable redis && \
    docker-php-ext-install pdo_mysql

RUN echo 'label ::1/128 0' > /etc/gai.conf
