name: Update Yarn Workflow
on:
  workflow_call:
    inputs:
      directory:
        type: string
        default: .
    secrets:
      GH_TOKEN:
        required: true
      PAT:
        required: true

jobs:
  update:
    name: Bump Yarn
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIT_AUTHOR_NAME: 'github-actions[bot]'
      GIT_AUTHOR_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
      GIT_COMMITTER_NAME: 'github-actions[bot]'
      GIT_COMMITTER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
      YARN_ENABLE_IMMUTABLE_INSTALLS : 'false'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Update version
        run: |
          directory=${{ inputs.directory }}

          old_version=$(cd "${directory#/}" && yarn --version)
          (cd "${directory#/}" && yarn set version latest)
          new_version=$(cd "${directory#/}" && yarn --version)

          if git diff --exit-code &> /dev/null; then
            exit 0
          fi

          (cd "${directory#/}" && yarn)
          title="Bump yarn from $old_version to $new_version in $directory"
          body="Bumps yarn from $old_version to $new_version in $directory."

          git checkout -b "dependencies/yarn${directory#.}/yarn-$new_version"
          git add "${directory#/}/package.json" "${directory#/}/yarn.lock" "${directory#/}/.yarnrc.yml" "${directory#/}/.yarn/"
          git commit --message="$title"
          git push origin HEAD

          gh pr create --base=master --title="$title" --body="$body"
